#+SETUPFILE: theme-readtheorg.setup
#+AUTHOR: Liu-Cheng Xu
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="home.css"/>


* 前言
说起验证码，脑海中首先浮现的是比较简单的 4 个数字验证码，进入知乎发现它的登录验证码现在是这样：点击倒立的汉字。

#+caption: 截取自知乎 2017.01.13
file:./img/zhihu_verification_code.png

如果是通过某个问题的链接进入知乎，它的验证码是下面这样，是一个 4 个数字与字母的组合:

#+caption: 截取自知乎 2017.01.14
file:./img/captcha2.png


搜索验证码识别等相关内容，有不少内容[fn:1] [fn:3] [fn:4][fn:5] ，不过这些内容大都是针对字母，数字等, 也就是第二幅图片中的验证码. 虽然我不熟悉 OCR, 也没做过验证码识别，不过套路应该都是差不多的, 识别数字，字母或者汉字的整个框架可能大同小异。

下述内容大都是 “搬运” 而来。

* 验证码识别思路
验证码识别的思路非常暴力[fn:2]，大概就是这样：

1. 去噪＋二值化
2. 字符分割
3. 每个字符识别

验证码的难度在这 3 步上都有反应。比如

1. 噪声：加一条贯穿全图的曲线，比如网格线，还有图的一半是白底黑字，另一半是黑底白字。
2. 分割：字符粘连，7和4粘在一起。
3. 识别：字符各种扭曲，各种旋转。

但相对而言，难度最大的是第 2 步，分割(这一点在 [fn:3] 也有体现，那些分割出的字符很多用肉眼都不易分辨 )。所以就有人想，我能不能不做分割，就把验证码给识别了。深度学习擅长做端到端的学习，因此这个不分割就想识别的事情交给深度学习是最合适的。

在评论部分，有人问项亮对知乎给出的点击倒立汉字验证码如何看？摘自他的回答：

#+BEGIN_QUOTE
因为整个常用汉字库其实也就6000多个字。可以根据字体库，不同的旋转，倒立，镜像，都去学习一遍。
#+END_QUOTE

也有人问他什么是 end to end? 这里是他的回答：

#+BEGIN_QUOTE
一般的任务要先通过feature engineering，从原始数据中提取特征。而如何提取特征对最终的效果很重要。而 end2end 强调的是不提特征，用原始数据。比如如果是图片的话，就用每个像素的 RGB 值。end2end 的系统，你只需要定义输入，Loss，剩下就听天由命了.
#+END_QUOTE


** 基于 CNN 的验证码识别
基于CNN去识别验证码，其实就是一个图片的多标签学习问题。比如考虑一个4个数字组成的验证码，那么相当于每张图就有4个标签。那么我们把原始图片作为输入，4个标签作为输出，扔进CNN里，看看能不能收敛就行了。

** 基于 LSTM+CTC 的验证码识别
LSTM＋CTC被广泛的用在语音识别领域把音频解码成汉字，从这个角度说，OCR其实就是把图片解码成汉字，并没有太本质的区别。而且在整个过程中，不需要提前知道究竟要解码成几个字。

* 图像预处理

* 训练样本

1. 验证码图像的预处理

  #+caption: 原始知乎验证码 captcha.gif
  file:./img/captcha.gif

  这一步就是将验证码图像中的一串字符进行切割得到单个字符。[fn:3] 在 README 中也说训练了一个分割器与识别器。 不过我看了 =train= 下的一些分割图片，仅以肉眼可辩的标准来看，切割的确有难度，很多人眼都不太容易认得清。 当然，我不知道这样在实际操作中是否已算是分割的 “不错”。
  #+caption: 将验证码图像进行字符切割得到单个字符
  file:./img/captcha_post.gif

2. 训练模型

   KNN/SVM

3. 识别


* 算法伪代码

** 分割

  需要准备一个用于比较的图片库 ~character_library~ [fn:6], 将验证码分割后的字符与图片库进行比较，找出最相近的字符进行输出。

  #+BEGIN_SRC c
  input：captcha, character_library
  output：predicted captcha

  chars := segment(captcha)

  for char in chars
      do    NN(char, character_library)
  #+END_SRC

这里的问题可能是：

- 分割字符。这一点上面也提到，大概与推荐系统中冷启动一样是个老大难.
- 获取比对的图片库. 如果只有数字或者字母，还好些，但是汉字，光常用字就有三千。此外还有各种形态的变化，倾斜，扭曲等。不过就知乎的验证码而言，倾斜与扭曲的程度似乎不太严重。 
- 如何选择模型。最简单的 KNN, 还有其他模型等。

** 不分割

如果不分割大概就是项亮文章的方法了。 说实话，我不太了解，但是感觉很强大.
  
* Footnotes

[fn:6] 如何高效识别验证码？https://www.zhihu.com/question/23026853

[fn:5] 端到端的OCR：LSTM＋CTC的实现 http://www.jianshu.com/p/4fadf629895b 

[fn:4] Neural Net CAPTCHA Cracker http://www.cs.sjsu.edu/faculty/pollett/masters/Semesters/Spring15/geetika/CS298%20Slides%20-%20PDF 

[fn:3] 知乎爬虫（验证码自动识别）https://github.com/moxiegushi/zhihu

[fn:2] 端到端的OCR：验证码识别 http://blog.xlvector.net/2016-05/mxnet-ocr-cnn/

[fn:1] 机器自动识别验证码的原理是怎么样的？https://www.zhihu.com/question/22479139
